### ISSUE TITLE
Error importi STIX in MISP via MISP/OpenTAXII

### ISSUE THREAD

**Issue by davidonzo** [MISP/MISP-Taxii-Server#15]
Tested on two separated engine.
I used the MISP VM available at the latest version.

```
{"timestamp": "2017-07-27T10:53:00.496235Z", "exception": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py\", line 83, in process
    response_message = handler.handle_message(self, message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 29, in handle_message
    request, service_id=service.id, version=11))
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/persistence/manager.py\", line 131, in create_inbox_message
    INBOX_MESSAGE_CREATED.send(self, inbox_message=entity)
  File \"/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py\", line 267, in send
    for receiver in self.receivers_for(sender)]
  File \"/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py\", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File \"/usr/local/lib/python3.5/dist-packages/misp_taxii_hooks-0.2-py3.5.egg/misp_taxii_hooks/hooks.py\", line 63, in post_stix
    package = pymisp.tools.stix.load_stix(content_block.content)
NameError: name 'content_block' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/dist-packages/Flask-0.12.2-py3.5.egg/flask/app.py\", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File \"/usr/local/lib/python3.5/dist-packages/Flask-0.12.2-py3.5.egg/flask/app.py\", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/middleware.py\", line 76, in wrapper
    return _process_with_service(service)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/middleware.py\", line 154, in _process_with_service
    response_message = service.process(request.headers, taxii_message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py\", line 89, in process
    in_response_to=message.message_id)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/exceptions.py\", line 48, in raise_failure
    tb=tb)
  File \"/usr/local/lib/python3.5/dist-packages/six.py\", line 685, in reraise
    raise value.with_traceback(tb)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py\", line 83, in process
    response_message = handler.handle_message(self, message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 29, in handle_message
    request, service_id=service.id, version=11))
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/persistence/manager.py\", line 131, in create_inbox_message
    INBOX_MESSAGE_CREATED.send(self, inbox_message=entity)
  File \"/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py\", line 267, in send
    for receiver in self.receivers_for(sender)]
  File \"/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py\", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File \"/usr/local/lib/python3.5/dist-packages/misp_taxii_hooks-0.2-py3.5.egg/misp_taxii_hooks/hooks.py\", line 63, in post_stix
    package = pymisp.tools.stix.load_stix(content_block.content)
opentaxii.taxii.exceptions.FailureStatus: name 'content_block' is not defined", "level": "warning", "event": "Status exception", "logger": "opentaxii.middleware"}
```

Similar error using "taxii-push" on the local server.

PS: finally the TAXII stream seems to work fine, many thanks for this! :-)

**Comment by FloatingGhost** [comment]
Fixed, you pulled at literally the worst moment you possibly could have.

**Comment by davidonzo** [comment]
Thanks a lot!
I'm going to test it again :+1: 

PS: I'm italian, from Sicily: I am the worst moment :-P

**Comment by Nymeria1** [comment]
Hi guys,
unfortunately I also have got the same problem.
Here below the error

> Posting STIX...
2017-07-27T15:21:40.045475Z [opentaxii.middleware] warning: Status exception {level=warning, logger=opentaxii.middleware, timestamp=2017-07-27T15:21:40.045475Z, event=Status exception, exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py", line 83, in process
    response_message = handler.handle_message(self, message)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 29, in handle_message
    request, service_id=service.id, version=11))
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/persistence/manager.py", line 131, in create_inbox_message
    INBOX_MESSAGE_CREATED.send(self, inbox_message=entity)
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/misp_taxii_hooks-0.2-py3.5.egg/misp_taxii_hooks/hooks.py", line 63, in post_stix
    package = pymisp.tools.stix.load_stix(content_block.content)
NameError: name 'content_block' is not defined

I have updated the project but the issue is present yet.
I do not find your fix.
Many thanks

**Comment by FloatingGhost** [comment]
christ on a bike it was broken for like 45 minutes and everyone pulled at once. 

You need to run `sudo python3 setup.py install` again to get the update to install, but as you can see on [the line referenced in your message](https://github.com/MISP/MISP-Taxii-Server/blob/master/misp_taxii_hooks/hooks.py#L63), the statement does not match the one in your error.

Therefore you have not updated.

**Comment by Nymeria1** [comment]
Thanks for the suggestion. In fact the line in my file does not match, but also if I execute the command
` sudo python3 setup.py install` or `git pull` the project does not update.
