### ISSUE TITLE
config.yaml can't be found in the repository

### ISSUE THREAD

**Issue by arcsector** [MISP/MISP-Taxii-Server#16]
In the installation instructions after setting up the databases you tell us to edit `config.yaml`, but if you do a simple find for it there is no such file. The only files that exist are `config.default.yaml` and `config.travis.yaml`, both located in `/config/`. New users should know which one to edit.

If you're referring to the OpenTAXII `config.yml`, I believe that has changed to be `defaults.yml`.

Thanks for the beautiful program! I love it and I'll continue reporting issues as I see them!

**Comment by FloatingGhost** [comment]
Clarified location of config file. I thought it was obvious but hey. It would be to me, I set it up.

>If you're referring to the OpenTAXII config.yml, I believe that has changed to be defaults.yml

Travis tests pass without warnings, leaving as-is.
