### ISSUE TITLE
Running open-TAXII server not in localhost

### ISSUE THREAD

**Issue by Nymeria1** [MISP/MISP-Taxii-Server#18]
Hi guys,
I am able to execute 
`opentaxii-run-dev`
without error. In fact service-discovery and push work correctly.
Now I would like to start the server not in localhost so I can get to the server from external taxii client.
I changed the config.yaml file with my domain server. 
Now I see in the log that the services are: my_domain/service/discovery for example and not localhost/service/discovery
However the server is running in 127.0.0.1:9000
How I solve this problem?
Many thanks for your help.

**Comment by FloatingGhost** [comment]
`0.0.0.0:9000` will bind on all interfaces, internal and external.

**Comment by FloatingGhost** [comment]
if that doesn't work, make sure you're actually exporting your OPENTAXII_CONFIG env var

**Comment by Nymeria1** [comment]
Yes I have tested both your solutions but they do not work.

This is my config.yaml 
`---
domain: "0.0.0.0:9000"
support_basic_auth: yes

save_raw_inbox_messages: yes
xml_parser_supports_huge_tree: yes
[...]`

and before starting the server I run:
`export OPENTAXII_CONFIG=/opt/MISP-Taxii-Server/config/config.yaml` 
 `export` PYTHONPATH=.`

**Comment by FloatingGhost** [comment]
Good, I do just love issues where you get config and just told it doesn't work

It really does make debugging and providing support super easy! 

I love vague issues last thing on a Friday, my favourite thing in the world.

Logs? Who needs logs? Not me apparently.

I am the magical repo maintainer, here to read your mind and debug without information!

**Comment by FloatingGhost** [comment]
I'm gonna go get alcohol. 

I *might* help you on monday if you're lucky and there's actual information here when I get into the office.

**Comment by Nymeria1** [comment]
Because the server works in localhost I do not know which logs you want and where I have to search it.
I am happy to tell you all information needed to solve the problem.
Thanks magical repo maintener.
Have nice weekend.

**Comment by FloatingGhost** [comment]
>Because the server works in localhost 

This changes **Nothing**, it's just a bind address.

[How Do I Deploy Opentaxii in production?](http://www.opentaxii.org/en/stable/running.html)

Literally one google away.

I'm going home.

**Comment by Nymeria1** [comment]
>I'm gonna go get alcohol.
>I might help you on monday if you're lucky and there's actual information here when I get into the office

Thanks. I solved the problem alone.
