### ISSUE TITLE
Instuctions out of date

### ISSUE THREAD

**Issue by arcsector** [MISP/MISP-Taxii-Server#21]
Hi there,

Sorry to bother you. Might not be an issue as you're pulling a specific commit from them, but the instructions are invalid as of 3 days ago; opentaxii changed their architecture so that the accounts are now stored in a yml file, the same one which now also stores the services and collections data.

In addition they no longer have the `opentaxii-create-accounts` function. Now you have to put the details for each account into the yml file and then use `opentaxii-sync-data`. Hope this helps!

**Comment by FloatingGhost** [comment]
It's not out of date as we haven't updated our dep commit :^)

`git clone --recursive` will pull the right version, and all will be right with the world.

I'll update it to the new architecture when I feel like dying more than usual.

**Comment by arcsector** [comment]
Sounds good. I didn't know where to let you know that they had updated it, so I put it here.
