### ISSUE TITLE
error: cybox 2.1.0.12 is installed but cybox<2.1.1.0,>=2.1.0.13.dev1 is required by set(['stix'])

### ISSUE THREAD

**Issue by trismegistusX** [MISP/MISP-Taxii-Server#23]
At finishing stages of installing MISP-TAXII-Server, error message appears stating not supported cybox version for MISP with reequired for MISP-TAXII:

Installed /usr/local/lib/python2.7/dist-packages/misp_taxii_hooks-0.2-py2.7.egg
Processing dependencies for misp-taxii-hooks==0.2
error: cybox 2.1.0.12 is installed but cybox<2.1.1.0,>=2.1.0.13.dev1 is required by set(['stix'])

Is this specific to python2.7 only or python3 too?
Can Cybox be upgraded without impacting MISP as a required version to run?

**Comment by FloatingGhost** [comment]
How many times do I need to write these words?

STOP. 

USING.

PYTHON.

2.

It works if you use a version of python that isn't 17 years old

**Comment by iglocska** [comment]
@FloatingGhost, I have a feeling you don't like Python 2 ;) 

But indeed, MISP-STIX is STIX 1.2, which is Python3.

**Comment by trismegistusX** [comment]
Installed the supported version:
{"cybox": "2.1.0.13", "stix": "1.2.0.2", "success": 1, "mixbox": "1.0.2"}

Push worked:
INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
INFO: Content block successfully pushed

Though MISP doesn't like it :)
STIX and Cybox libraries....OK
STIX library version....Incorrect STIX version installed, found 1.2.0.2, expecting 1.1.1.4
CYBOX library version....Incorrect CyBox version installed, found 2.1.0.13, expecting 2.1.0.12
MIXBOX library version....OK

Next instance will be only python3, I promise!!

**Comment by trismegistusX** [comment]
Received the following error when pushing sample stix file to MISP:
`
2017-11-06 21:42:30,928 requests.packages.urllib3.connectionpool DEBUG: Starting new HTTP connection (1): localhost
2017-11-06 21:42:30,934 requests.packages.urllib3.connectionpool DEBUG: http://localhost:9000 "POST /services/inbox HTTP/1.1" 200 306
2017-11-06 21:42:30,937 cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="7149768213953236338" in_response_to="0" status_type="UNAUTHORIZED"/>

2017-11-06 21:42:30,937 cabby.cli.commons ERROR: UNAUTHORIZED: 
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "build/bdist.linux-x86_64/egg/cabby/cli/push.py", line 51, in _runner
    client.push(content, binding, collection_names=args.collections, uri=path)
  File "build/bdist.linux-x86_64/egg/cabby/client11.py", line 332, in push
    service_type=const.SVC_INBOX)
  File "build/bdist.linux-x86_64/egg/cabby/abstract.py", line 205, in _execute_request
    timeout=self.timeout)
  File "build/bdist.linux-x86_64/egg/cabby/dispatcher.py", line 91, in send_taxii_request
    raise UnsuccessfulStatusError(obj)
UnsuccessfulStatusError: UNAUTHORIZED:
`
Added taxii auth user to config.yaml:
---
domain: "localhost:9000"
support_basic_auth: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://user:password@localhost/taxiipersist
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://user:password@localhost/taxiiauth
    create_tables: yes
    secret: SupersecretstringforOpenTaxiiserverinsertedhere

logging:
  opentaxii: info
  root: info

hooks: misp_taxii_hooks.hooks
# Sample configuration for misp_taxii_server

zmq:
    host: localhost
    port: 50000

misp:
    url: "https://xx.xx.xx.xx"
    api: apikey
    verifySSL: False

taxii:
    auth:
        username: username
        password: password
    collections:
        - collection

`
Added another taxii user and updated config.yaml and same "Unauthorized" error.
(Used same credentials for taxii auth as in taxiiauthDB and taxiipersistDB)

Config env:
OPENTAXII_CONFIG=/home/user/MISP-Taxii-Server/config/config.yaml

Alert when file pushed to opentaxii-run-dev:
UnauthorizedException: UNAUTHORIZED, level=warning, timestamp=2017-11-06T21:42:30.932239Z, logger=opentaxii.middleware, event=Status exception}
127.0.0.1 - - [06/Nov/2017 21:42:30] "POST /services/inbox HTTP/1.1" 200 -

Pushed file:
taxii-push --path http://localhost:9000/services/inbox -f /home/user/MISP-Taxii-Server/tests/sample.xml -v  --dest collection --user taxii --password password

Adding new taxii auth accounts and update config.yaml file to test fails, what is the next step?
