### ISSUE TITLE
Question: Push/Poll Setup

### ISSUE THREAD

**Issue by johestephan** [MISP/MISP-Taxii-Server#25]
Hello all,
I have planed to use MISP-Taxii-Server to interconnect my MISP platform with a SIEM solution,
so that the SIEM solution polls indicators out of MISP.

Somehow I got lost in the setup and currently I question myself if that even works. Starting with that MISP-Taxii-Serveronly runs on 127.0.0.1 (even when I change to 0.0.0.0).

Any hint or guidance?

**Comment by FloatingGhost** [comment]
>Hello all

Just me here my dude
Me and far too much STIX

>runs on 127.0.0.1 (even when I change to 0.0.0.0).

That should be adequate for testing. 

If you want to access externally, you shouldn't be using the dev server, and should instead by using [gunicorn production server](http://www.opentaxii.org/en/stable/running.html)

**Comment by johestephan** [comment]
And you are more then enough :-)

Thanks, will try that

**Comment by FloatingGhost** [comment]
Nothing here for nearly a month - is it all working and OK to close this?

**Comment by davidonzo** [comment]
Just to suggest to use gunicorn for workers and service management.
To explose OpenTAXII server, I use gunicorn with nginx as reverse proxy.

This solved the poor opentaxii logging system and permitted a better management of the opentaxii routes (for example I don't want to expose the /management/heath URL that note require authentication).

Just used the suggestions found in the official gunicorn documentation.

**Comment by FloatingGhost** [comment]
Assuming fixed. Closing.
