### ISSUE TITLE
taxii-proxy failure 

### ISSUE THREAD

**Issue by UOITGeorge** [MISP/MISP-Taxii-Server#29]
I'm attempting to populate the taxii server so i can push it into MISP later. 
My command looks like this 
taxii-proxy              --poll-path http://hailataxii.com/taxii-data              --poll-collection guest.Lehigh_edu              --inbox-path http://localhost:9000/services/inbox              --inbox-collection collection              --binding  urn:stix.mitre.org:xml:1.1 
Every feed i'm connecting to will eventually fail with the following message 
ERROR: FAILURE: There was a failure while executing the message handler.
I saw on another post that changing collate to latin1_general_ci could help , but it didn't help in my case . 
If i change the server to test.taxiistand.com and use one of the available collections there it will take longer but will fail eventually with the same error 

If there is another way to populate taxii server using any possible commands i'm ready to give it a try. 

Thanks

**Comment by FloatingGhost** [comment]
A few things

1. you should probably redact your collection name, we now all know where you work ;)
2. I've never used taxii-proxy, but hey debugging shouldn't be so hard

You haven't attached any sort of log - the taxii server you run should say *why* there was an error. Can you give me that?

**Comment by UOITGeorge** [comment]
Not sure what you mean by redacting the collection name 
As far as the log file , this was the first thing i was trying to look for , but i don't see any logs being created when i use taxii-proxy script . Am i missing something ? 
Is there any other (simple) way to populate the DB ?
Thank you

**Comment by FloatingGhost** [comment]
>Not sure what you mean by redacting the collection name

never mind, misread

Ok so I just tried it and it works just fine.

Steps to do what I did:

- Start up local taxii server, `OPENTAXII_CONFIG=<path to config> opentaxii-run-dev`
- Run the command

```
taxii-proxy \
  --poll-path http://hailataxii.com/taxii-data \
  --poll-collection guest.Abuse_ch \
  --inbox-path http://localhost:9000/services/inbox \
  --inbox-collection collection \
  --inbox-username user \
  --inbox-password pass
```

With no server logs from the taxii server itself there's nothing more I can debug

**Comment by UOITGeorge** [comment]
Is there a way to enable the server logs? 
The only thing i was able to do is to redirect the output to a file . by adding -v &>output.log 
[output.log](https://github.com/MISP/MISP-Taxii-Server/files/1496577/output.log)
The log shows that it fails after adding 4 objects successfully

**Comment by FloatingGhost** [comment]
I asked for the *SERVER* logs, not the proxy client ones.

See my desktop, the server logs are printed to stdout when using `opentaxii-run-dev`, telling you everything you need to know. 

Server on the left, proxy client on the right.

![2017-11-22-155142](https://user-images.githubusercontent.com/4086403/33136526-5b6e68a4-cf9d-11e7-86d9-a1f4ddfb1221.png)

**Comment by UOITGeorge** [comment]
[server2.log](https://github.com/MISP/MISP-Taxii-Server/files/1496851/server2.log)
The log is not generated . I have redirected the output of the opentaxii-run-dev to server2.log (attached) 
Looks like this si the same information like in your screenshot 
Is this the correct one ? 

Thank you

**Comment by FloatingGhost** [comment]
You're using outdated code, this was an issue with pymisp removing an internal function I relied on.

```bash
git pull
sudo python3 setup.py install
```

and try again

**Comment by UOITGeorge** [comment]
Thank you 
Updating the code worked

**Comment by UOITGeorge** [comment]
Now , after  running for some time the script crashes with the following message 
2017-11-22 22:44:37,353 ERROR: StartTag: invalid element name, line 95071, column 2 (<string>, line 95071)
[server3.zip](https://github.com/MISP/MISP-Taxii-Server/files/1497722/server3.zip)

**Comment by FloatingGhost** [comment]
Well I mean that's not my log format, and its not in your server log.

As my side works (as expected) I'm closing this issue.
