### ISSUE TITLE
MISP events not populating with attributes

### ISSUE THREAD

**Issue by tee-dog** [MISP/MISP-Taxii-Server#34]
Hi,

Can someone help me with an issue I am having with populating MISP events with attributes please?

I successfully installed the repo and managed to pull stix files. However, when pushing them out to my MISP instance, some events have no attributes assigned.

I suspected this might be related to [this issue](https://github.com/MISP/MISP-Taxii-Server/issues/11) but my hooks.py already takes events with >0 attributes into consideration.

Interestingly, some STIX files populate just fine like this one
`        <cybox:Observable id="example:observable-b57aa65f-9598-04fb-a9d1-5094c36d5dc4">
            <cybox:Object id="example:object-f4fac80a-1239-47cc-b0e6-771b1a73f817">
                <cybox:Properties xsi:type="AddressObject:AddressObjectType" category="ipv4-addr">
                    <AddressObject:Address_Value>198.51.100.17</AddressObject:Address_Value>
                </cybox:Properties>
            </cybox:Object>
`

While others don't like this one
`    
<stix:Observables cybox_major_version="2" cybox_minor_version="1" cybox_update_version="0">
        <cybox:Observable id="fsisac:Observable-711fd835-067f-4d7f-9f5b-d16ad5a7034f">
            <cybox:Title>Address: randomsuspiciousemail@icloud.com</cybox:Title>
            <cybox:Description>Malicious Email Address</cybox:Description>
            <cybox:Object id="fsisac:Address-7e43d07c-952d-42b0-83ca-31cf1715e3f0">
                <cybox:Properties xsi:type="AddressObj:AddressObjectType" category="e-mail">
                    <AddressObj:Address_Value condition="Equals">randomsuspiciousemail@icloud.com</AddressObj:Address_Value>
                </cybox:Properties>
            </cybox:Object>
        </cybox:Observable>
    </stix:Observables>
`

![image](https://user-images.githubusercontent.com/21217391/34678937-6f750e7a-f48c-11e7-816e-4f1b3db2a48f.png)

The second states an "AddressObj:Address_Value condition="Equals" for each attribute - would that cause any issues?

Output of the debugger mode of gunicorn:
`Posting STIX...
/usr/local/lib/python2.7/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
Building Event...
Using title STIX Import
STIX loaded succesfully.
Extracted ['randomsuspiciousemail@icloud.com']
Checking for existence of randomsuspiciousemail@icloud.com
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
randomsuspiciousemail@icloud.com is unique, we'll keep it
Uploading event to MISP with attributes ['randomsuspiciousemail@icloud.com']
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`

I re-pulled the repo but it says it's already up-to-date. Sorry if I missed any log information, please let me know. Is there anything that can be done to fix this?

[services.yaml.txt](https://github.com/MISP/MISP-Taxii-Server/files/1612076/services.yaml.txt)
[config.yaml.txt](https://github.com/MISP/MISP-Taxii-Server/files/1612077/config.yaml.txt)
[hooks.py.txt](https://github.com/MISP/MISP-Taxii-Server/files/1612055/hooks.py.txt)

**Comment by tee-dog** [comment]
I did some more checks and believe MISP does not like email addresses within this particular (fsisac) STIX format. IPs are no problem and translate into MISP event attributes, email addresses don't. Would anybody know how this can be fixed? I assume buildMISPAttribute.py is where the magic happens...

**Comment by tee-dog** [comment]
Thank you, you are really helpful! I have pulled and re-installed MISP-STIX-Converter but the error persists (event created with no attributes). Could you please try again with the attached samples?

I'm puzzled, it should really be caught by your new line
> 
        else:
            mispEvent.add_attribute("email-src", ast_eval(str(obj.address_value)),
                                    comment=pkg.title or None)


sorry about the Python, we upgraded the box but it's not having any of it ;-)

Push-success:
> root@lbg-cuckoobox:~/MISP-Taxii-Server/FSISAC/stix_files# taxii-push --path http://localhost:9000/services/inbox -f system.Default_STIX111_2018_01_05T11_24_54_703983_00_00.xml --dest collection --username taxii --password misptaxii1
2018-01-17 10:34:05,912 INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
2018-01-17 10:34:06,693 INFO: Content block successfully pushed

Gunicorn event log:
> {"hooks": "misp_taxii_hooks.hooks", "logger": "opentaxii.server", "event": "signal_hooks.imported", "timestamp": "2018-01-17T10:33:11.767578Z", "level": "info"}
{"timestamp": "2018-01-17T10:33:11.767823Z", "logger": "opentaxii.server", "event": "opentaxii.server_configured", "level": "info"}
("'dGF4aWk6bWlzcHRheGlpMQ=='", 24)
Posting STIX...
/usr/local/lib/pythonlookaunicorn!/dist-packages/stix/utils/deprecated.py:48: UserWarning: The use of this field has been deprecated. Received 'datetime' object.
  warnings.warn(msg)
Building Event...
Using title STIX Import
STIX loaded succesfully.
Extracted ['randomemail@icloud.com']
Checking for existence of nicholasholmberg@icloud.com
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
randomemail@icloud.com is unique, we'll keep it
Uploading event to MISP with attributes ['randomemail@icloud.com']
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[not_working.xml.txt](https://github.com/MISP/MISP-Taxii-Server/files/1638675/not_working.xml.txt)
[working.xml.txt](https://github.com/MISP/MISP-Taxii-Server/files/1638676/working.xml.txt)

**Comment by FloatingGhost** [comment]
Bizarrely `not_working.xml` *does* work for me


![2018-01-17-112422](https://user-images.githubusercontent.com/4086403/35040544-64ff67e4-fb79-11e7-9862-de49351b11e3.png)


MISP 2.4.81, but that shouldn't matter

Maybe Python's messing with you, try
```bash
sudo pip uninstall misp_stix_converter
cd /path/to/MISP-STIX-Converter
sudo python setup.py install
# Restart TAXII server
```

might work

**Comment by tee-dog** [comment]
and it totally does, than you ever so much! how does this "turn-it-off-and-on-again" thing still work lol
