### ISSUE TITLE
MISP and Taxii-Server on the same box

### ISSUE THREAD

**Issue by robertnixon2003** [MISP/MISP-Taxii-Server#35]
Just a question. Is there anything to consider if you are running the Taxii Server on the same box as MISP? We are trying to pull in indicators from external entities.

**Comment by FloatingGhost** [comment]
The only possible difficulty would be webserver configuration - if you run Taxii on port 443 you'd have to set it up to pass to both MISP and the TAXII server, but theoretically it's doable
