### ISSUE TITLE
start/end timezone issue

### ISSUE THREAD

**Issue by SHSauler** [MISP/MISP-Taxii-Server#40]
Dates miss `tzinfo` just by providing `%Y-%m-%d` and error gets raised:

```
    raise ValueError('%s.tzinfo must not be None!' % varname)
```

Fixed it with 
```
import pytz
[...]
poll_from = datetime.strptime(args.start, "%Y-%m-%d%Z").replace(tzinfo=pytz.utc)
```

But then only UTC can be selected. Would this be okay? Then I'll submit this as PR.

Kind regards!

**Comment by FloatingGhost** [comment]
oh goodie timezones, my favourite

gimme 5 I'll fix it

**Comment by FloatingGhost** [comment]
Added `--tz` option in 52337596dc11a28a

e.g

` python3 scripts/run-taxii-poll.py -s --tz Europe/London` 

Defaults to UTC if not provided

**Comment by SHSauler** [comment]
Thank you kindly!
