### ISSUE TITLE
MISP to TAXII push fails - push_published_to_taxii.py

### ISSUE THREAD

**Issue by rmeghnagi** [MISP/MISP-Taxii-Server#41]
Hi all,

when i try to pushing my events from MISP to Taxii with the script "push_published_to_taxii.py" i receive this message:

root@misp:/MISP-Taxii-Server/scripts# push_published_to_taxii.py
INFO [push_published_to_taxii.py:20 - <module>() ] Starting...
INFO [push_published_to_taxii.py:35 - <module>() ] Subscribing to tcp://localhost:50000
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...
INFO [push_published_to_taxii.py:57 - <module>() ] Recieved a message!
INFO [push_published_to_taxii.py:61 - <module>() ] Ignoring misp_json_self...

This message continue until I stop the script...

Any suggestion is welcome!
Thank you

**Comment by FloatingGhost** [comment]
What exactly do you want me to do? This is entirely expected behaviour

**Comment by FloatingGhost** [comment]
no response, assuming all works as intended (spoiler: it does)
