### ISSUE TITLE
Events pushed by Python Scritpt are not inserted on MISP

### ISSUE THREAD

**Issue by rmeghnagi** [MISP/MISP-Taxii-Server#51]
Hi to all,

I wrote a Python script using Cabby API. The script retrieves some content from a source and writes it to a collection (basically a taxii-proxy is executed but i had to develop a custom script beacuse of the taxii-proxy command does not accept some auth-options).

The problem is, while if I execute a taxii-push command from CLI (getting content from a file) an event appears on the MISP platform, if I execute my custom script the event does not appear. 

Do you have any tips?

**Comment by FloatingGhost** [comment]
>please debug my script that I haven't given you and the details of which are incredibly vague

>oh also I'm not going to give you any logs

I swear to god is it *THAT* hard!?

**Comment by adulau** [comment]
@rmeghnagi Could you share technical information such output of logs, Python exceptions or technical details or even the source of your script? That would help us to debug your issue. Thank you.

**Comment by rmeghnagi** [comment]
@adulau Do you have any suggestion? Thank you in advance!

**Comment by adulau** [comment]
Could you save/print the STIX file and try to import manually using the import in MISP directly? The STIX 1.1 import in MISP has been significantly improved. If you could share the file that would be great too. Thanks.

**Comment by rmeghnagi** [comment]
I'm looking for a way to automate the STIX import in MISP from a certain source. For this reason i wrote this Python script. I cannot understand which is the difference between the taxii-push command and the push inside the script. The first event is loaded in MISP, not the second one.

**Comment by rmeghnagi** [comment]
Resolved.

Thank you all.

**Comment by adulau** [comment]
Cool thank you for the feedback.
