### ISSUE TITLE
Duplicate Checking Not Working

### ISSUE THREAD

**Issue by bricksolid** [MISP/MISP-Taxii-Server#53]
Disclaimer: I am no expert, but this is an issue I had and fixed it with the change below. 

The duplication check was always saying the value was a duplicate and will be ignored. 
I found the logic in the misp_taxii_hook/hooks.py not evaluating correctly. 
Starting at line 66:
for attrib in values:
        log.info("Checking for existence of %s", attrib)
        search = MISP.search("attributes", values=str(attrib))
        **if search["response"] !=  []:**
            # This means we have it!
            log.info("%s is a duplicate, we'll ignore it.", attrib)
            package.attributes.pop([x.value for x in package.attributes].index(attrib))
        else:
            log.info("%s is unique, we'll keep it", attrib)

When I looked at the json response it is always "not empty" because the object attribute is in the response object. Example for empty responses: {'response': {'Attribute': []}}

I fixed this by adding evaluating the attribute object as well. 
 for attrib in values:
        log.info("Checking for existence of %s", attrib)
        search = MISP.search("attributes", values=str(attrib))
            **if search["response"]["Attribute"]:**
           # This means we have it!
            log.info("%s is a duplicate, we'll ignore it.", attrib)
            package.attributes.pop([x.value for x in package.attributes].index(attrib))
        else:
            log.info("%s is unique, we'll keep it", attrib)

So far the issue of it saying everything is duplicate is gone and if there is a duplication, it appropriately does not add it. 

Please review and see if this is the proper way to fix the hooks script.

**Comment by FloatingGhost** [comment]
Running against MISP 2.4.94 duplicate checking works as intended.
