### ISSUE TITLE
authentication_required can i set this parameter to no

### ISSUE THREAD

**Issue by dp1975** [MISP/MISP-Taxii-Server#59]
Hello 
i am trying to do the following command without user & password
taxii-poll --host xx.xx.xx.xx --port 9000 --path /services/poll --collection collection --username yyy --password ffff
- i set the parameter  authentication_required to no in the config.yaml ,but it does not work.
someone can advise me please.
thank you

**Comment by FloatingGhost** [comment]
I do not recall ever documenting an `authentication_required` parameter, mainly because it would do nothing and is never expected anywhere.

OpenTaxii does not support open authentication. If you must, just create an account with username/password of guest/guest (as hailataxii does)
