### ISSUE TITLE
Change OpenTaxii server from HTTP to HTTPS

### ISSUE THREAD

**Issue by dp1975** [MISP/MISP-Taxii-Server#60]
Hello
i need that my  opentaxii server  will work with https and not http .
i can not find any details information how to do it.
can someone explain me how to do it.
i am using gunicorn. 
example for the poll command:
 taxii-poll --host localhost --port 9000 --path /services/poll --collection collection --username xxxx --password xxxx
result:
INFO: Sending Poll_Fulfillment to http://xx.xx.xx.xx:9000/services/poll

thank you
dp

**Comment by FloatingGhost** [comment]
Refer to [opentaxii documentation](http://www.opentaxii.org/en/stable/running.html)
