### ISSUE TITLE
KeyError: 'auth':    in   push_published_to_taxii.py

### ISSUE THREAD

**Issue by faustus25** [MISP/MISP-Taxii-Server#62]
Original error when using config.default.yaml:

````
Traceback (most recent call last):
  File "/usr/local/bin/push_published_to_taxii.py", line 48, in <module>
    cli.set_auth(username = config["taxii"]["auth"]["username"],
KeyError: 'taxii'

````

> see: config.travis.yaml
> 
> copy config from there.
> 
> _Originally posted by @FloatingGhost in https://github.com/MISP/MISP-Taxii-Server/issues/4#issuecomment-304103263_
> 

Error when using config.travis.yaml:

````
Traceback (most recent call last):
  File "../MISP-Taxii-Server/scripts/push_published_to_taxii.py", line 48, in <module>
    cli.set_auth(username = config["auth"]["username"],
KeyError: 'auth'

````

Can you amend the script "push_published_to_taxii.py"?

**Comment by FloatingGhost** [comment]
Your two snippets display different code being run, would I be correct in assuming you changed the script yourself? 

`config["taxii"]["auth"]["username"]` is the correct config path

Provided you have your environment variables set as per the README and haven't changed the structure of the config file or amended the script, it will find the key.

The script itself does not need amending

**Comment by faustus25** [comment]
Wait, there would need to be 2 config yaml files referenced to OPENTAXII_CONFIG (config.default.yaml and config.travis.yaml)

"run-taxii-poll.py" works when referencing config.default.yaml or config.yaml as you describe in the README:

> Now, with that data, copy config/config.default.yaml over to config/config.yaml and open it

BUT in order to run "push_published_to_taxii.py", you need to update/use config.travis.yaml instead and then update the OPENTAXII_CONFIG to this yaml file which doesn't include the "Collections" section like in config.default.yaml

Checked there and that "push_published_to_taxii.py" works when OPENTAXII_CONFIG=~/config.travis.yaml

It would be better to have 2 separate OPENTAXII_CONFIGs referenced, one unique to each script CONFIG1 & CONFIG2

OPENTAXII_CONFIG1=~/config.default.yaml
OPENTAXII_CONFIG2=~/config.travis.yaml

**Comment by FloatingGhost** [comment]
I think you've misinterpreted my comments

The comment in #4 was because `config.default.yaml` did not yet exist. The `config.travis.yaml` file is solely for travis CI, and is not a config file for you to use.

You should be using one singular file at `config.yaml`, which should be based on `config.default.yaml`, which is why I say to copy it. It's a skeleton config.

**Comment by faustus25** [comment]
Therein lies the issue: "config.yaml" (config.default.yaml) works with "run-taxii-poll.py" (without modification) while config.travis.yaml (without modification) works with "push_published_to_taxii.py.

In any case, I will use config.yaml solely for "run-taxii-poll.py".
