### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by WednesdayAd** [MISP/MISP-Taxii-Server#66]
Hello!
I've try to push MISP events to the TAXII server with scripts/push_published_to_taxii.py. 
I get an error when using this script. Maybe I do simething wrong. Help me please.
I received this:

/home/admin/MISP-Taxii-Server/scripts# python3 push_published_to_taxii.py
Traceback (most recent call last):
  File "push_published_to_taxii.py", line 48, in <module>
    cli.set_auth(username = config["taxii"]["auth"]["username"],
TypeError: 'NoneType' object is not subscriptable

**Comment by FloatingGhost** [comment]
Sing it with me now!

>here's a story you all know well
it's one of an person who forgot to tell
the script where his config file was located,
and raised an issue as if it was so complicated

>wooahhahhh export the environment variable! (it's in the readme!)
woooahahah this is unbearable! 
woahhahahh you've gotta RTFM! (So many issues!)
wowooahah it'll work then

**Comment by WednesdayAd** [comment]
I can read. I have all needed parameters. And thaths why I ask.
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_US.UTF-8
SUDO_GID=1004
OLDPWD=/home/admin
USERNAME=root
SUDO_COMMAND=/bin/su
USER=root
PWD=/home/admin/MISP-Taxii-Server
HOME=/root
SUDO_USER=admin
SUDO_UID=1000
MAIL=/var/mail/root
OPENTAXII_CONFIG=/home/admin/MISP-Taxii-Server/config/config.yaml
SHELL=/bin/bash
TERM=xterm
SHLVL=1
PYTHONPATH=.
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LESSOPEN=| /usr/bin/lesspipe %s
