### ISSUE TITLE
Issuing with Polling

### ISSUE THREAD

**Issue by kknagesh** [MISP/MISP-Taxii-Server#70]
Hello I am trying to run the "run-taxii-poll.py", mentioning the taxii feed information in remote-server.yaml file, i am getting the following error, can some one help me fixing the issue
cabby.exceptions.AmbiguousServicesError: 2 services found with type 'POLL'. Specify the exact URI

The feed i configured in the remote-server has two services with the same name "POLL" but with a different  polling url.

Can someone help me in fixing the issue

**Comment by FloatingGhost** [comment]
Run

```bash
taxii-discovery \
  --host <HOST TO POLL>
  --port <POLLING PORT>
  --discovery <DISCOVERY PATH, sometimes /taxii-discovery-service, may vary>
```

run `git pull` on this repository, which will update `scripts/run-taxii-poll.py`

Then you can follow [a new FAQ entry](https://github.com/MISP/MISP-Taxii-Server#ambigious-polling-service) to resolve this ambiguity

**Comment by kknagesh** [comment]
Thanks alot.. This fixed the issue.
