### ISSUE TITLE
Issue with Format when loading to MISP

### ISSUE THREAD

**Issue by kknagesh** [MISP/MISP-Taxii-Server#71]
Hello Team, We have MISP Application running and we are loading the data from the taxii server installed on the same server.

The data is being published to the MISP but not in the correct format.
For Example => The Title says the "Card is comprimised" in the source (when i check the data in the taxii database :sqlite), however when it is published to MISP, it says STIX Import.

Can you please let me know if some settings has to be change on Taxii Server to fix the issue

**Comment by FloatingGhost** [comment]
>Hello Team

No team here. Just me an a library of dusty STIX files, incomprehensible scrawlings on the wall with the only readable text just being "XML" written over and over again, slowly becoming less and less coherent until becoming just scratches in the pool of lost sanity

More relevant for [MISP-STIX-Converted](https://github.com/MISP/MISP-STIX-Converter)

The title is set by:
```python
def buildEvent(pkg, **kwargs):
    log.info("Building Event...")
    if not pkg.stix_header:
        title = "STIX Import"
    else:
        if not pkg.stix_header.title:
            title = "STIX Import"
        else:
            title = pkg.stix_header.title
    log.info("Using title %s", title)

event = mispevent.MISPEvent()
event.info = title
```

so provided your inbound STIX files are properly formatted it should add the correct title

**Comment by kknagesh** [comment]
@FloatingGhost  - what i noticed was the stix content block has observables and indicators. However it is just loading the observables. I am currently using stix 1.1.1, however the content which we received is stix 1.2 and when i ran the taxiihook.py by passing the content block as an input parameter i am only getting the attributes which are there in the observables. 
I am attaching a sample file here.
[test.txt](https://github.com/MISP/MISP-Taxii-Server/files/2900862/test.txt)

see the output

misp_taxii_hooks# python3 hooksbkp.py
{
  "Event": {
    "Attribute": [
      {
        "category": "Network activity",
        "disable_correlation": false,
        "to_ids": true,
        "type": "ip-dst",
        "uuid": "50348163-6dcd-41f3-8488-3a38d854c7a2",
        "value": "31.31.31.108"
      },
      {
        "category": "Network activity",
        "disable_correlation": false,
        "to_ids": true,
        "type": "url",
        "uuid": "caa61999-f164-4764-a5ad-851f0ff2201f",
        "value": "http://xyz.info/nopy/admin.php"
      },
      {
        "category": "Network activity",
        "disable_correlation": false,
        "to_ids": true,
        "type": "domain",
        "uuid": "d08c637e-1973-4e84-a4ef-67f69becde27",
        "value": "xyz.info"
      }
    ],
    "analysis": "0",
    "distribution": "3",
    "info": "STIX Import",
    "threat_level_id": "2"
  }
}

**Comment by FloatingGhost** [comment]
>However it is just loading the observables

again more suited to the converter repo than here

This is intended behaviour - STIX is a leviathan which is nothing short of hellish to coherently parse into anything else, and the converter currently employed by MISP will only attempt to extract subclasses of `cybox.core.observable.Observable` since even that requires more complexity than I'd like

If you want to extend it, by all means do and submit a PR

**Comment by kknagesh** [comment]
Thanks..
