### ISSUE TITLE
Manual Intallation

### ISSUE THREAD

**Issue by garrit-schroeder** [MISP/MISP-Taxii-Server#72]
Hello,

i just completed the installation of this project.

One step is missing in the manual.

I've been using the MISP VM v2.4.103 and i had to install additionally: 
sudo apt-get install libmysqlclient-dev
or recent versions of debian/ubuntu (as of 2018) it is
sudo apt install default-libmysqlclient-dev

found here: https://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found

**Comment by FloatingGhost** [comment]
It's not missing, it's 

![](https://i.imgur.com/Y3ZGqTR.png)

right there

but it should probably be above the pip operation
