### ISSUE TITLE
opentaxii-sync-data: command not found

### ISSUE THREAD

**Issue by WednesdayAd** [MISP/MISP-Taxii-Server#73]
Hello.
I tried to run the synchronization command according to the instructions
`opentaxii-sync-data config/data-configuration.yaml`
but it didn't work out for me, and i've this
`opentaxii-sync-data: command not found`
I will be glad to any help.

**Comment by FloatingGhost** [comment]
> tried to run the synchronization command according to the instructions

no you didn't. please follow the instructions. you *very clearly* do not have opentaxii installed.

**Comment by spencertang0709** [comment]
> 
> 
> Hello.
> I tried to run the synchronization command according to the instructions
> `opentaxii-sync-data config/data-configuration.yaml`
> but it didn't work out for me, and i've this
> `opentaxii-sync-data: command not found`
> I will be glad to any help.

also got this issue by following instruction. any hint where i missed?

**Comment by EricSoldierer** [comment]
I don't get why serious issues are being down voted. I followed the documentation exactly step by step together with a colleague and we are having the same issue.

**Comment by iwitz** [comment]
Has the same issue. The executable had been installed in /usr/local/bin which wasn't in $PATH.
I had to either fix my $PATH environment variable or call the executable with its full path, /usr/local/bin/opentaxii-sync-data
