### ISSUE TITLE
TAXII UNAUTHORIZED

### ISSUE THREAD

**Issue by krishnamohan152** [MISP/MISP-Taxii-Server#91]
# Hi,  I am getting the following error, “{opentaxii.exceptions.UnauthorizedException: UNAUTHORIZED}”. 
### When I am trying to poll [or] push the data, After setting up the installation as per provided instructions of MISP TAXII. I am adding the following configuration files for further reference  
Config.yml 
---
domain: "localhost:9000"
support_basic_auth: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:{somepassword}@localhost/taxiipersist
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:{somepassword}@localhost/taxiiauth
    create_tables: yes
    secret: ILoveTheSecretStringIsIsGreatButNeedsToBeChangedFrienderino

logging:
  opentaxii: info
  root: info

hooks: misp_taxii_hooks.hooks
# Sample configuration for misp_taxii_server

zmq:
    host: localhost
    port: 50000

misp:
    url: "Some URL"
    api: Auth Key
    verifySSL: False

taxii:
    auth:
        username: admin
        password: admin
    collections:
        - my_collection

ill already exported the OPENTAXII_CONFIG, PYTHON ENV, and DEV ENV
![image](https://user-images.githubusercontent.com/28926789/104274194-4e5e6900-54c6-11eb-92f6-3e8077976b77.png)

# Results
### TAXII POLL
![image](https://user-images.githubusercontent.com/28926789/104273676-2c181b80-54c5-11eb-85be-51eda8d3433f.png)

### TAXII PUSH
![image](https://user-images.githubusercontent.com/28926789/104273756-51a52500-54c5-11eb-88c2-9d7c5f8073da.png)

#### I tried to check the database entries, whether user are storing into TAXIIAUTH or not, Yes it is storing. After referring the ISSUE BLOG, I understood I tried to run the 
                                             OPENTAXII-CREATE-ACCOUNT -u admin -p admin -a
And I am getting the following error

![image](https://user-images.githubusercontent.com/28926789/104273313-aac08900-54c4-11eb-936a-0055dad66869.png)

Kindly suggested me, What alternatives i can look

**Comment by chmason13** [comment]
I am also having this issue. Any help would be greatly appreciated.

**Comment by kalanisanders** [comment]
Identical issue here too. I also tried:

opentaxii-update-account -u admin -f password -v admin

**Comment by kalanisanders** [comment]
It appears to be an issue with upstream OpenTaxii maybe? I was also getting the following error message after starting the server:

{"token": "XXXXXXXXXXXXXXXXXXXX", "event": "Can not decode a token", "logger": "opentaxii.auth.sqldb.api", "level": "warning", "timestamp": "2021-01-27T18:00:17.826383Z"}

The token did decode properly when I tested it and matched my secret.


Here's my quick and dirty fix, two files:

```
--- /orig/OpenTAXII/opentaxii/auth/sqldb/api.py   2021-01-27 19:39:11.918350852 +0000
+++ /MISP-Taxii-Server/env/lib/python3.8/site-packages/opentaxii/auth/sqldb/api.py        2021-01-27 18:18:30.346070291 +0000
@@ -110,7 +110,7 @@

     def _get_account_id(self, token):
         try:
-            payload = jwt.decode(token, self.secret)
+            payload = jwt.decode(token, self.secret, algorithms=["HS256"])
         except jwt.ExpiredSignatureError:
             log.warning('Invalid token used', token=token)
             return

```



```
--- /orig/OpenTAXII/opentaxii/management.py       2021-01-27 19:39:11.922351035 +0000
+++ /MISP-Taxii-Server/env/lib/python3.8/site-packages/opentaxii/management.py    2021-01-27 17:34:20.339295619 +0000
@@ -20,7 +20,8 @@
     if not token:
         abort(401)

-    return jsonify(token=token.decode('utf-8'))
+    #return jsonify(token=token.decode('utf-8'))
+    return jsonify(token=token)


 @management.route('/health', methods=['GET'])
```

**Comment by krishnamohan152** [comment]
i'll quickly check this is hack and update the status here

**Comment by krishnamohan152** [comment]
I tried with the provided solution and it is working perfectly fine. Thanks @kalanisanders

**Comment by derwilliwonka** [comment]
Hey folks,
Experiencing the same problem. Is this fix still up-to-date or is it just dumbass me who cant find the files?
Thanks in advance.

**Comment by SanyaKapoor** [comment]
I applied the a similar fix to the one mentioned on this thread by @kalanisanders. It solves the issue for me, also opened a [pull request ](https://github.com/eclecticiq/OpenTAXII/pull/184)for the same on opentaxii's repo, do check it out once it should work for you!

**Comment by LFED-FP** [comment]
This works
